"""initial migration

Revision ID: c8ad178e2de2
Revises: 68937f929907
Create Date: 2021-09-04 13:52:02.935302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ad178e2de2'
down_revision = '68937f929907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'verified')
    # ### end Alembic commands ###
